### ISSUE TITLE
menu keys

### ISSUE THREAD

**Issue by Cyan4973** [czodroid/droid48sx#1]
Great to see activity on this excellent emulator !

I wanted to use this opportunity to ask for a feature which I miss from the PC port of Emu48, if I may.

When clicking on a menu item on the screen, droid48sx consider it to be just a normal part of the screen, and therefore raises the option menu.

On the PC version of emu48, some skins make this action equivalent to pressing the underlying key (ABCDEF).

This feature looks even more useful and natural on a touch screen. It makes menu-driven interaction with HP48SX more fluid.

**Comment by czodroid** [comment]
This is indeed a good idea,
I'll look at it when I have some spare time!

  Olivier.

**Comment by czodroid** [comment]
This is indeed a good idea,
I'll look at it when I have some spare time!

Olivier.

2016-02-05 1:31 GMT+01:00 Yann Collet notifications@github.com:

**Comment by Cyan4973** [comment]
Is this feature request abandoned ?

**Comment by czodroid** [comment]
Yes, this feature is abandoned. I did took time for the bug fixes, and now the letter A and F are the same size of other keys. And know, you can get the 48s by installing Emu48 for Android (written by Regis Cosnier).

**Comment by Cyan4973** [comment]
> now, you can get the 48s by installing Emu48 for Android (written by Regis Cosnier).

Do you mean you intend to stop maintaining droid48sx in the future ?

**Comment by czodroid** [comment]
No, I won't stop maintaining droid48sx in the future.

But if you want, you can get Emu48...
