### ISSUE TITLE
Add 48GX version

### ISSUE THREAD

**Issue by SammysHP** [czodroid/droid48sx#2]
From the visual experience this fork is much better that the original version of Droid48. Although there were some commits at Droid48, I think that this fork has much more potential.

Since I don't really like the GUI of Droid48 and you've made some awesome graphics, I'd like to ask if it would be possible for you to create a 48GX version of your fork.

Even better would be a collaboration between you and @shagr4th and maybe – as it is open source – other developers. I'm not sure in which way I can help because my time is very limited at the moment and I haven't fully understood the integration of native code.

**Comment by czodroid** [comment]
I'll do only the HP 48s...You can get the 48g, 49g and 50g by installing Emu48 for Android (written by Regis Cosnier).
