### ISSUE TITLE
Screen pixel scaling

### ISSUE THREAD

**Issue by dbgrande** [czodroid/droid48sx#4]
Would it be possible to bring back integer pixel scaling for the calculator screen—maybe as an option?

On my phone with 720x1280 resolution, the line widths of the characters now vary between 5 and 6 pixels.
I had some screenshots from 2017 that show it used to have consistent line widths of 5 pixels.

I like the taller A-F keys, but the inconsistent line widths just don't look right.

**2017 version (calculator screen pixels consistent 5 phone pixels wide):**
![48sx_2017](https://user-images.githubusercontent.com/64602967/177190379-6d262363-0987-4a17-8b2c-e5a296d465a7.png)

**2022 version (calculator screen pixels vary between 5 or 6 phone pixels wide)**
![48sx_2022](https://user-images.githubusercontent.com/64602967/177190414-f23cd7bf-c6ec-40b2-9634-3edc9601db3d.png)

**Comment by czodroid** [comment]
Yes !
I would replace 'HP48 screen is larger in some situations' with 'HP48 LCD screen is scaled to full pixels' and the option would become inactive for new users.
I noticed that the option 'HP48 screen is larger in some situations' did not work as expected. This is now fixed. Wait for a new version...

**Comment by dbgrande** [comment]
Thanks, I just got the update and it looks good.

My real HP48 died some twenty years ago, but this is the next best thing.

**Comment by czodroid** [comment]
mine too !

see you,
